/** Rows extracted from Tracking note 2026 May-Jun.xlsx (Sheet1). */
export const TRACKING_NOTE_REAL_ROWS = [
  ['Hercules Hercules', 'headcount', 'adult(F4)', 'CB'],
  ['L1', '0', '1', '', '28th December 2025: Male'],
  ['L2', '0', '', ''],
  ['L3', '0', '', ''],
  [''],
  ['lamprima adolphinae', 'headcount', 'adult(F4+)', 'CB', 'Eggs:17'],
  ['L1', '0', '6', '', '3 males'],
  ['L2', '0', '', '', '3 females'],
  ['L3', '16', '', ''],
  [''],
  ['Calcosoma.M', 'headcount', 'adult', 'WD'],
  ['L1', '0', '1', '', 'Jan 4th: 90mm male'],
  ['L2', '0', '', '', 'Started eating: March 12th'],
  ['L3', '0', '', ''],
  [''],
  ['Giraffe.K', 'headcount', 'adult', 'CB'],
  ['L1', '0', '4', '', 'Jun 17th: 80mm male'],
  ['L2', '0', '', '', 'Jun 20th: 60mm male'],
  ['L3', '8', '', '', 'Jun 20th: 39mm female'],
  ['', '', '', '', 'May 19th: 35mm female'],
  ['H.Perryi', 'headcount', 'adult', 'CB'],
  ['L1', '0', '2', ''],
  ['L2', '0', '', ''],
  ['L3', '0', '', ''],
  ['Musimon', 'headcount', 'adult', 'CB', ''],
  ['L1', '0', '1(Male)', ''],
  ['L2', '0', '', ''],
  ['L3', '0', '', ''],
];
